version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: mcp-redis-test
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  mongodb:
    image: mongo:6
    container_name: mcp-mongodb-test
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 3

  lnbits:
    image: lnbitsdocker/lnbits:latest
    container_name: mcp-lnbits-test
    environment:
      - LNBITS_BACKEND_WALLET_CLASS=LndRestWallet
      - LNBITS_ADMIN_UI=true
      - LNBITS_SITE_TITLE=MCP Test LNBits
      - LNBITS_DEBUG=true
    ports:
      - "5001:5000"
    volumes:
      - lnbits-data:/app/data
    depends_on:
      - redis
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: mcp-prometheus-test
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - fee-optimizer
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  fee-optimizer:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mcp-fee-optimizer-test
    environment:
      - MCP_ENV=test
      - LNBITS_URL=http://lnbits:5000
      - LNBITS_API_KEY=${LNBITS_API_KEY:-replacewithvalidkey}
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB=mcp_test
    volumes:
      - .:/app
    command: python scripts/fee_optimizer_scheduler.py --dry-run
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      lnbits:
        condition: service_healthy

  metrics-exporter:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mcp-metrics-exporter-test
    environment:
      - MCP_ENV=test
      - LNBITS_URL=http://lnbits:5000
    ports:
      - "9091:9091"
    volumes:
      - .:/app
    command: python scripts/setup_prometheus_metrics.py --port 9091
    depends_on:
      - fee-optimizer

volumes:
  redis-data: {}
  mongodb-data: {}
  lnbits-data: {}
  prometheus-data: {} 