app = "mcp-backend"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DRY_RUN = "true"

[mounts]
  source = "mcp_data"
  destination = "/app/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"] 