global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'fee-optimizer'
    static_configs:
      - targets: ['fee-optimizer:9090']

  - job_name: 'metrics-exporter'
    static_configs:
      - targets: ['metrics-exporter:9091']
