# Configuration Prometheus pour MCP Production - Version simplifiée
# Dernière mise à jour: 7 janvier 2025

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Monitoring de l'API MCP
  - job_name: 'mcp-api'
    static_configs:
      - targets: ['mcp-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Auto-monitoring Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoring Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s


