version: '3.8'

services:
  lnbits:
    image: lnbitsdocker/lnbits:latest
    container_name: mcp-lnbits-test
    environment:
      - LNBITS_BACKEND_WALLET_CLASS=LndRestWallet
      - LNBITS_ADMIN_UI=true
      - LNBITS_SITE_TITLE=MCP Test LNBits
      - LNBITS_DEBUG=true
    ports:
      - "5001:5000"
    volumes:
      - lnbits-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: mcp-prometheus-test
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - fee-optimizer
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3

  fee-optimizer:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mcp-fee-optimizer-test
    environment:
      - MCP_ENV=test
      - LNBITS_URL=http://lnbits:5000
      - LNBITS_API_KEY=${LNBITS_API_KEY:-replacewithvalidkey}
    volumes:
      - .:/app
    command: python scripts/fee_optimizer_scheduler.py --dry-run
    depends_on:
      lnbits:
        condition: service_healthy

  metrics-exporter:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: mcp-metrics-exporter-test
    environment:
      - MCP_ENV=test
      - LNBITS_URL=http://lnbits:5000
    ports:
      - "9091:9091"
    volumes:
      - .:/app
    command: python scripts/setup_prometheus_metrics.py --port 9091
    depends_on:
      - fee-optimizer

volumes:
  lnbits-data: {}
  prometheus-data: {} 