#!/bin/bash
# Setup Security Hooks for MCP
# Generated by Claude Code - Security Audit
# 🔒 Installs and configures pre-commit security hooks

set -e

echo "🔒 Setting up MCP Security Hooks..."
echo "=================================="

# Check if we're in the right directory
if [ ! -f "README.md" ] || [ ! -d "src" ]; then
    echo "❌ Please run this script from the MCP root directory"
    exit 1
fi

# Install pre-commit if not already installed
if ! command -v pre-commit &> /dev/null; then
    echo "📦 Installing pre-commit..."
    pip install pre-commit
else
    echo "✅ pre-commit already installed"
fi

# Install detect-secrets if not already installed
if ! command -v detect-secrets &> /dev/null; then
    echo "📦 Installing detect-secrets..."
    pip install detect-secrets
else
    echo "✅ detect-secrets already installed"
fi

# Install bandit for security scanning
if ! python -c "import bandit" 2>/dev/null; then
    echo "📦 Installing bandit..."
    pip install bandit
else
    echo "✅ bandit already installed"
fi

# Install black and isort for formatting
if ! python -c "import black" 2>/dev/null; then
    echo "📦 Installing black..."
    pip install black
else
    echo "✅ black already installed"
fi

if ! python -c "import isort" 2>/dev/null; then
    echo "📦 Installing isort..."
    pip install isort
else
    echo "✅ isort already installed"
fi

# Create secrets baseline if it doesn't exist
if [ ! -f ".secrets.baseline" ]; then
    echo "🔍 Creating secrets baseline..."
    detect-secrets scan --all-files --disable-plugin AbsolutePathDetectorExperimental > .secrets.baseline
    echo "✅ Secrets baseline created"
else
    echo "✅ Secrets baseline already exists"
fi

# Install pre-commit hooks
echo "🔗 Installing pre-commit hooks..."
pre-commit install

# Run pre-commit on all files to test
echo "🧪 Testing pre-commit hooks..."
if pre-commit run --all-files; then
    echo "✅ All pre-commit hooks passed!"
else
    echo "⚠️  Some pre-commit hooks failed. Please fix the issues and try again."
    echo "💡 You can run 'pre-commit run --all-files' to see detailed errors."
fi

# Update .gitignore with security entries
echo "📝 Updating .gitignore..."
cat >> .gitignore << 'EOF'

# ================================
# SECURITY - NEVER COMMIT THESE
# ================================
*.env
*.env.*
!*.env.example*
!*.env.template*
secrets/
credentials/
keys/
*.key
*.pem
*.p12
*.pfx
bandit-report.json

# Temporary files
*.tmp
*.temp
*~

# IDE files
.vscode/settings.json
.idea/

# OS files
.DS_Store
Thumbs.db
EOF

echo "✅ .gitignore updated with security rules"

# Create security reminder
cat > SECURITY_REMINDER.md << 'EOF'
# 🔒 SECURITY REMINDERS

This file is automatically created by the security setup.

## Before Each Commit
- [ ] Run `pre-commit run --all-files` to check for security issues
- [ ] Ensure no real secrets are in your changes
- [ ] Use `CHANGE_ME` placeholders in example files
- [ ] Test your changes in a secure environment

## Regular Security Tasks
- [ ] Weekly: Update dependencies with security patches
- [ ] Monthly: Rotate secrets and API keys
- [ ] Quarterly: Security audit and penetration testing

## Security Tools Installed
- ✅ pre-commit: Prevents insecure commits
- ✅ detect-secrets: Scans for hardcoded secrets
- ✅ bandit: Python security static analysis
- ✅ black & isort: Code formatting for consistency

## Emergency Security Contacts
- Security Team: [ADD YOUR CONTACT]
- Incident Response: [ADD YOUR CONTACT]

## Resources
- Security Documentation: README_SECURITE.md
- Incident Response Plan: [ADD LINK]
- Security Training: [ADD LINK]
EOF

echo "📋 Created SECURITY_REMINDER.md"

# Final check
echo ""
echo "🎉 Security setup completed!"
echo "=================================="
echo ""
echo "✅ Pre-commit hooks installed and configured"
echo "✅ Security scanning tools installed"
echo "✅ Git hooks will now prevent insecure commits"
echo ""
echo "📋 Next steps:"
echo "1. Review and commit the security configuration files"
echo "2. Train your team on the new security workflow"
echo "3. Set up regular security audits and secret rotation"
echo "4. Test the setup by trying to commit a file with 'password=secret123'"
echo ""
echo "⚠️  Remember: These hooks are your first line of defense, not a replacement for security awareness!"