# Configuration Qdrant pour MCP Production
# Dernière mise à jour: 7 mai 2025

service:
  http_port: 6333
  grpc_port: 6334

storage:
  # Stockage persistant sur disque
  storage_path: /qdrant/storage
  
  # Configuration des performances
  performance:
    max_search_threads: 4
    max_optimization_threads: 2
  
  # Configuration de la mémoire
  memory:
    # Taille du cache des segments en MB
    segment_cache_size: 512
    # Taille du cache des vecteurs en MB
    vector_cache_size: 256

# Configuration de l'API
api:
  enable_cors: false
  max_request_size_mb: 32

# Configuration du clustering (désactivé pour single node)
cluster:
  enabled: false

# Logging
log_level: INFO

# Configuration des sauvegardes
telemetry:
  disabled: true

# Configuration de sécurité (optionnelle)
# service:
#   api_key: "your-api-key-here" 